agent:
  name: Nyxora-EVM-Agent
  default_chain: sepolia
llm:
  provider: gemini
  model: gemini-2.5-flash
  temperature: 0.2
  credentials:
    gemini_key: AIzaSyCDDwEpOafxM3Uuz81is79HkiFuuWFLV58
memory:
  type: file
  path: ./memory.json
integrations:
  telegram:
    enabled: true
    bot_token: 8841811642:AAEsuI8TLJ12BObisEUfN9KW3XEsQaXo3nQ
